name: Grade the Pull Request
on:
  workflow_run:
    workflows: ["PR Management"]
    types:
      - completed
  pull_request_target:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    environment: CTF
    steps:
      - name: Checkout head branch of PR
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Checkout main branch of this repo
        uses: actions/checkout@v3
        with:
          ref: main
          path: ./grading
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
      - name: Grade the Pull Request
        run: |
          gem install octokit
          ruby grading/script/grading.rb
        env:
          FLAG: ${{ secrets.FLAG }}
